### ISSUE TITLE
store bcrypt secret variable in your config.env

### ISSUE THREAD

**Issue by dupreesi** [fac-15/FAC_guidebook2.0#39]
should push that one up to github.
I know no one told u... should never be visible in your handlers 
The best way to store secrets in your app is not to store secrets in your app (check that
https://medium.com/poka-techblog/the-best-way-to-store-secrets-in-your-app-is-not-to-store-secrets-in-your-app-308a6807d3ed)

**Comment by tantsandras** [comment]
Ja we knew about that but we ran out of time to move it haha
